
* Benchmarks Selection
** Restrictions

- # qubits < 17
- # gates as spread as possible and in the case of repeated benchmark the minimum number of gates
- The less number of the same algorithm versions as possible
- The benchmarks that are repeated and have an interesting combination of No. qubits/No. gates are preferred
- The benchmarks with a known functionality are preferred


** Selected (/for now/)

43 benchmarks (with qubits numbers from 3 to 17 qubits) selected after applying the previous Restrictions to the analysis of the benchmarks described in the next section.

| No. qubits | No. gates | Algorithm                        |
|------------+-----------+----------------------------------|
|          5 |        27 | 4gt11_82                         |
|          6 |       228 | 4gt12-v1_89                      |
|          6 |       258 | 4gt4-v0_72                       |
|          7 |        70 | 4mod5-bdd_287                    |
|          5 |        20 | 4mod5-v0_20                      |
|          7 |        84 | alu-bdd_288                      |
|          5 |        36 | alu-v0_27                        |
|         17 |        35 | benstein_vazirani_15b_secret_128 |
|         16 |       175 | +cnt3-5_179+                       |
|          5 |         7 | cuccaroAdder_1b                  |
|          7 |        11 | cuccaroMultiplier_1b             |
|          6 |        73 | decod24-bdd_294                  |
|          6 |       338 | decod24-enable_126               |
|          6 |         5 | graycode6_47                     |
|         13 |    360618 | +ground_state_estimation_10+       |
|          3 |        20 | ham3_102                         |
|          5 |       233 | hwb4_49                          |
|         10 |       200 | +ising_model_10+                   |
|         11 |     22445 | +life_238+                         |
|          3 |        50 | miller_11                        |
|          5 |       288 | mini-alu_167                     |
|         10 |       173 | +mini_alu_305+                     |
|          5 |       178 | mod10_176                        |
|          6 |       555 | mod5adder_127                    |
|          5 |        22 | mod5d1_63                        |
|          6 |       440 | mod8-10_177                      |
|          5 |       132 | one-two-three-v1_99              |
|          5 |        70 | one-two-three-v3_101             |
|         13 |    128744 | +plus63mod4096_163+                |
|         10 |       110 | +qft_10+                           |
|          4 |        34 | rd32-v0_66                       |
|          6 |       781 | sf_274                           |
|          6 |       778 | sf_276                           |
|         12 |      4792 | shor_15                          |
|         12 |      3009 | sqrt8_260                        |
|         13 |      1993 | +squar5_261+                       |
|         15 |      7630 | +square_root_7+                    |
|          7 |      3888 | sym6_145                         |
|         14 |       270 | +sym6_316+                         |
|          8 |     80480 | +urf2_152+                         |
|          8 |     20112 | +urf2_277+                         |
|          8 |        12 | vbeAdder_2b                      |
|          6 |         7 | xor5_254                         |


*After simulating the algorithms, some of them either return errors (segmentation fault) or are computationally exhausting to simulate them as they should be simulated.
  
** Analysis before selection

*** Initial entries

690


*** Benchark amounts depending on the different possible number of qubits

#+BEGIN_EXAMPLE

            Benchmarks ammount
No. qubits
3                           12
4                           12
5                           57
6                           31
7                           22
8                           16
9                           15
10                          21
11                          17
12                          14
13                          18
14                          17
15                          16
16                          14
17                          10

#+END_EXAMPLE

*** Different gate numbers for algorithms with less than 17 qubits

#+BEGIN_EXAMPLE

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 27, 28, 29, 31, 33, 34, 35, 36, 37, 43, 50, 51, 52, 53, 66, 68, 69, 70, 73, 83, 84, 85, 91, 103, 107, 110, 115, 131, 132, 146, 148, 150, 151, 162, 163, 164, 173, 175, 178, 179, 194, 200, 211, 215, 217, 228, 230, 231, 233, 235, 244, 247, 251, 258, 263, 270, 272, 273, 275, 288, 290, 296, 320, 326, 328, 338, 342, 343, 395, 403, 440, 451, 467, 469, 485, 504, 555, 580, 612, 631, 650, 778, 781, 954, 986, 1043, 1206, 1221, 1291, 1336, 1776, 1914, 1993, 3009, 3073, 3213, 3439, 3888, 4813, 5321, 6050, 6723, 7630, 8763, 9462, 10223, 10619, 11414, 13658, 17159, 17936, 18852, 20112, 21504, 22445, 24379, 27126, 33827, 34881, 38046, 38577, 49829, 54766, 64283, 69380, 80480, 125362, 128744, 164416, 171840, 184864, 187112, 207775, 360618, 423488, 512064]

#+END_EXAMPLE

*** Amount of different no. of gates unique values

157

*** Amount of becnhmarks depending on the number of qubits and gates

#+BEGIN_EXAMPLE

                      Benchmarks ammount
No. qubits No. gates
3          6                           7
           7                           1
           19                          1
           20                          1
           36                          1
           50                          1
4          8                           6
           9                           2
           34                          1
           36                          1
           51                          1
           52                          1
5          4                           1
           7                           1
           10                          5
           11                          3
           18                          1
           20                          1
           21                          1
           22                          1
           23                          1
           27                          1
           35                          2
           36                          2
           37                          5
           52                          1
           53                          1
           66                          1
           68                          1
           69                          3
...                                  ...
13         128744                      1
           360618                      1
14         28                          1
           29                          8
           211                         1
           270                         1
           1776                        2
           11414                       1
           33827                       1
           38577                       1
           187112                      1
15         31                          8
           37                          1
           343                         1
           4813                        1
           7630                        1
           8763                        1
           9462                        1
           17936                       1
           171840                      1
16         33                          8
           175                         1
           272                         1
           326                         1
           485                         1
           10619                       1
           18852                       1
17         35                          8
           36                          1
           43                          1

[180 rows x 1 columns]

#+END_EXAMPLE

*** with names

#+BEGIN_EXAMPLE

No. qubits No. gates Algorithm
3          6         benstein_vazirani_1b_secret_128 
                     benstein_vazirani_1b_secret_16  
                     benstein_vazirani_1b_secret_2   
                     benstein_vazirani_1b_secret_32  
                     benstein_vazirani_1b_secret_4   
                     benstein_vazirani_1b_secret_64  
                     benstein_vazirani_1b_secret_8   
           7         benstein_vazirani_1b_secret_1   
           19        ex-1_166                        
           20        ham3_102                        
           36        3_17_13                         
           50        miller_11                       
4          8         benstein_vazirani_2b_secret_128 
                     benstein_vazirani_2b_secret_16  
                     benstein_vazirani_2b_secret_32  
                     benstein_vazirani_2b_secret_4   
                     benstein_vazirani_2b_secret_64  
                     benstein_vazirani_2b_secret_8   
           9         benstein_vazirani_2b_secret_1   
                     benstein_vazirani_2b_secret_2   
           34        rd32-v0_66                      
           36        rd32-v1_68                      
           51        decod24-v0_38                   
           52        decod24-v2_43                   
5          4         vbeAdder_1b                     
           7         cuccaroAdder_1b                 
           10        benstein_vazirani_3b_secret_128 
                     benstein_vazirani_3b_secret_16  
                     benstein_vazirani_3b_secret_32  
                     benstein_vazirani_3b_secret_64  
...                                                       ...
15         4813      misex1_241                      
           7630      square_root_7                   
           8763      ham15_107                       
           9462      dc2_222                         
           17936     co14_215                        
           171840    urf6_160                        
16         33        benstein_vazirani_14b_secret_1  
                     benstein_vazirani_14b_secret_128
                     benstein_vazirani_14b_secret_16 
                     benstein_vazirani_14b_secret_2  
                     benstein_vazirani_14b_secret_32 
                     benstein_vazirani_14b_secret_4  
                     benstein_vazirani_14b_secret_64 
                     benstein_vazirani_14b_secret_8  
           175       cnt3-5_179                      
           272       qft_16                          
           326       ising_model_16                  
           485       cnt3-5_180                      
           10619     inc_237                         
           18852     mlp4_245                        
17         35        benstein_vazirani_15b_secret_1  
                     benstein_vazirani_15b_secret_128
                     benstein_vazirani_15b_secret_16 
                     benstein_vazirani_15b_secret_2  
                     benstein_vazirani_15b_secret_32 
                     benstein_vazirani_15b_secret_4  
                     benstein_vazirani_15b_secret_64 
                     benstein_vazirani_15b_secret_8  
           36        vbeAdder_5b                     
           43        cuccaroAdder_7b                 

#+END_EXAMPLE


