python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 0410184_169 ../benchmarks/RevLib/QASM_compiled/0410184_169.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 0410184_169_scheduled ../benchmarks/RevLib/QASM_compiled/0410184_169_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 3_17_13 ../benchmarks/RevLib/QASM_compiled/3_17_13.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 3_17_13_scheduled ../benchmarks/RevLib/QASM_compiled/3_17_13_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4_49_16 ../benchmarks/RevLib/QASM_compiled/4_49_16.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4_49_16_scheduled ../benchmarks/RevLib/QASM_compiled/4_49_16_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt10-v1_81 ../benchmarks/RevLib/QASM_compiled/4gt10-v1_81.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt10-v1_81_scheduled ../benchmarks/RevLib/QASM_compiled/4gt10-v1_81_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt11_82 ../benchmarks/RevLib/QASM_compiled/4gt11_82.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt11_82_scheduled ../benchmarks/RevLib/QASM_compiled/4gt11_82_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt11_83 ../benchmarks/RevLib/QASM_compiled/4gt11_83.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt11_83_scheduled ../benchmarks/RevLib/QASM_compiled/4gt11_83_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt11_84 ../benchmarks/RevLib/QASM_compiled/4gt11_84.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt11_84_scheduled ../benchmarks/RevLib/QASM_compiled/4gt11_84_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v0_86 ../benchmarks/RevLib/QASM_compiled/4gt12-v0_86.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v0_86_scheduled ../benchmarks/RevLib/QASM_compiled/4gt12-v0_86_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v0_87 ../benchmarks/RevLib/QASM_compiled/4gt12-v0_87.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v0_87_scheduled ../benchmarks/RevLib/QASM_compiled/4gt12-v0_87_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v0_88 ../benchmarks/RevLib/QASM_compiled/4gt12-v0_88.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v0_88_scheduled ../benchmarks/RevLib/QASM_compiled/4gt12-v0_88_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v1_89 ../benchmarks/RevLib/QASM_compiled/4gt12-v1_89.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt12-v1_89_scheduled ../benchmarks/RevLib/QASM_compiled/4gt12-v1_89_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13_90 ../benchmarks/RevLib/QASM_compiled/4gt13_90.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13_90_scheduled ../benchmarks/RevLib/QASM_compiled/4gt13_90_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13_91 ../benchmarks/RevLib/QASM_compiled/4gt13_91.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13_91_scheduled ../benchmarks/RevLib/QASM_compiled/4gt13_91_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13_92 ../benchmarks/RevLib/QASM_compiled/4gt13_92.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13_92_scheduled ../benchmarks/RevLib/QASM_compiled/4gt13_92_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13-v1_93 ../benchmarks/RevLib/QASM_compiled/4gt13-v1_93.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt13-v1_93_scheduled ../benchmarks/RevLib/QASM_compiled/4gt13-v1_93_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_72 ../benchmarks/RevLib/QASM_compiled/4gt4-v0_72.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_72_scheduled ../benchmarks/RevLib/QASM_compiled/4gt4-v0_72_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_73 ../benchmarks/RevLib/QASM_compiled/4gt4-v0_73.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_73_scheduled ../benchmarks/RevLib/QASM_compiled/4gt4-v0_73_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_78 ../benchmarks/RevLib/QASM_compiled/4gt4-v0_78.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_78_scheduled ../benchmarks/RevLib/QASM_compiled/4gt4-v0_78_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_79 ../benchmarks/RevLib/QASM_compiled/4gt4-v0_79.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_79_scheduled ../benchmarks/RevLib/QASM_compiled/4gt4-v0_79_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_80 ../benchmarks/RevLib/QASM_compiled/4gt4-v0_80.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v0_80_scheduled ../benchmarks/RevLib/QASM_compiled/4gt4-v0_80_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v1_74 ../benchmarks/RevLib/QASM_compiled/4gt4-v1_74.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt4-v1_74_scheduled ../benchmarks/RevLib/QASM_compiled/4gt4-v1_74_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt5_75 ../benchmarks/RevLib/QASM_compiled/4gt5_75.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt5_75_scheduled ../benchmarks/RevLib/QASM_compiled/4gt5_75_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt5_76 ../benchmarks/RevLib/QASM_compiled/4gt5_76.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt5_76_scheduled ../benchmarks/RevLib/QASM_compiled/4gt5_76_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt5_77 ../benchmarks/RevLib/QASM_compiled/4gt5_77.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4gt5_77_scheduled ../benchmarks/RevLib/QASM_compiled/4gt5_77_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-bdd_287 ../benchmarks/RevLib/QASM_compiled/4mod5-bdd_287.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-bdd_287_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-bdd_287_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v0_18 ../benchmarks/RevLib/QASM_compiled/4mod5-v0_18.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v0_18_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-v0_18_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v0_19 ../benchmarks/RevLib/QASM_compiled/4mod5-v0_19.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v0_19_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-v0_19_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v0_20 ../benchmarks/RevLib/QASM_compiled/4mod5-v0_20.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v0_20_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-v0_20_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v1_22 ../benchmarks/RevLib/QASM_compiled/4mod5-v1_22.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v1_22_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-v1_22_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v1_23 ../benchmarks/RevLib/QASM_compiled/4mod5-v1_23.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v1_23_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-v1_23_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v1_24 ../benchmarks/RevLib/QASM_compiled/4mod5-v1_24.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod5-v1_24_scheduled ../benchmarks/RevLib/QASM_compiled/4mod5-v1_24_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod7-v0_94 ../benchmarks/RevLib/QASM_compiled/4mod7-v0_94.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod7-v0_94_scheduled ../benchmarks/RevLib/QASM_compiled/4mod7-v0_94_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod7-v1_96 ../benchmarks/RevLib/QASM_compiled/4mod7-v1_96.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 4mod7-v1_96_scheduled ../benchmarks/RevLib/QASM_compiled/4mod7-v1_96_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 9symml_195 ../benchmarks/RevLib/QASM_compiled/9symml_195.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b 9symml_195_scheduled ../benchmarks/RevLib/QASM_compiled/9symml_195_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b adr4_197 ../benchmarks/RevLib/QASM_compiled/adr4_197.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b adr4_197_scheduled ../benchmarks/RevLib/QASM_compiled/adr4_197_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b aj-e11_165 ../benchmarks/RevLib/QASM_compiled/aj-e11_165.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b aj-e11_165_scheduled ../benchmarks/RevLib/QASM_compiled/aj-e11_165_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-bdd_288 ../benchmarks/RevLib/QASM_compiled/alu-bdd_288.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-bdd_288_scheduled ../benchmarks/RevLib/QASM_compiled/alu-bdd_288_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v0_26 ../benchmarks/RevLib/QASM_compiled/alu-v0_26.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v0_26_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v0_26_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v0_27 ../benchmarks/RevLib/QASM_compiled/alu-v0_27.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v0_27_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v0_27_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v1_28 ../benchmarks/RevLib/QASM_compiled/alu-v1_28.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v1_28_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v1_28_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v1_29 ../benchmarks/RevLib/QASM_compiled/alu-v1_29.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v1_29_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v1_29_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_30 ../benchmarks/RevLib/QASM_compiled/alu-v2_30.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_30_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v2_30_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_31 ../benchmarks/RevLib/QASM_compiled/alu-v2_31.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_31_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v2_31_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_32 ../benchmarks/RevLib/QASM_compiled/alu-v2_32.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_32_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v2_32_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_33 ../benchmarks/RevLib/QASM_compiled/alu-v2_33.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v2_33_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v2_33_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v3_34 ../benchmarks/RevLib/QASM_compiled/alu-v3_34.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v3_34_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v3_34_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v3_35 ../benchmarks/RevLib/QASM_compiled/alu-v3_35.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v3_35_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v3_35_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v4_36 ../benchmarks/RevLib/QASM_compiled/alu-v4_36.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v4_36_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v4_36_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v4_37 ../benchmarks/RevLib/QASM_compiled/alu-v4_37.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b alu-v4_37_scheduled ../benchmarks/RevLib/QASM_compiled/alu-v4_37_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b C17_204 ../benchmarks/RevLib/QASM_compiled/C17_204.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b C17_204_scheduled ../benchmarks/RevLib/QASM_compiled/C17_204_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b clip_206 ../benchmarks/RevLib/QASM_compiled/clip_206.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b clip_206_scheduled ../benchmarks/RevLib/QASM_compiled/clip_206_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm152a_212 ../benchmarks/RevLib/QASM_compiled/cm152a_212.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm152a_212_scheduled ../benchmarks/RevLib/QASM_compiled/cm152a_212_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm42a_207 ../benchmarks/RevLib/QASM_compiled/cm42a_207.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm42a_207_scheduled ../benchmarks/RevLib/QASM_compiled/cm42a_207_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm82a_208 ../benchmarks/RevLib/QASM_compiled/cm82a_208.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm82a_208_scheduled ../benchmarks/RevLib/QASM_compiled/cm82a_208_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm85a_209 ../benchmarks/RevLib/QASM_compiled/cm85a_209.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cm85a_209_scheduled ../benchmarks/RevLib/QASM_compiled/cm85a_209_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cnt3-5_179 ../benchmarks/RevLib/QASM_compiled/cnt3-5_179.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cnt3-5_179_scheduled ../benchmarks/RevLib/QASM_compiled/cnt3-5_179_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cnt3-5_180 ../benchmarks/RevLib/QASM_compiled/cnt3-5_180.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cnt3-5_180_scheduled ../benchmarks/RevLib/QASM_compiled/cnt3-5_180_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b co14_215 ../benchmarks/RevLib/QASM_compiled/co14_215.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b co14_215_scheduled ../benchmarks/RevLib/QASM_compiled/co14_215_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b con1_216 ../benchmarks/RevLib/QASM_compiled/con1_216.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b con1_216_scheduled ../benchmarks/RevLib/QASM_compiled/con1_216_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cs ../benchmarks/RevLib/QASM_compiled/cs.txt
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cycle10_2_110 ../benchmarks/RevLib/QASM_compiled/cycle10_2_110.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b cycle10_2_110_scheduled ../benchmarks/RevLib/QASM_compiled/cycle10_2_110_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b dc1_220 ../benchmarks/RevLib/QASM_compiled/dc1_220.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b dc1_220_scheduled ../benchmarks/RevLib/QASM_compiled/dc1_220_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b dc2_222 ../benchmarks/RevLib/QASM_compiled/dc2_222.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b dc2_222_scheduled ../benchmarks/RevLib/QASM_compiled/dc2_222_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-bdd_294 ../benchmarks/RevLib/QASM_compiled/decod24-bdd_294.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-bdd_294_scheduled ../benchmarks/RevLib/QASM_compiled/decod24-bdd_294_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-enable_126 ../benchmarks/RevLib/QASM_compiled/decod24-enable_126.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-enable_126_scheduled ../benchmarks/RevLib/QASM_compiled/decod24-enable_126_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v0_38 ../benchmarks/RevLib/QASM_compiled/decod24-v0_38.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v0_38_scheduled ../benchmarks/RevLib/QASM_compiled/decod24-v0_38_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v1_41 ../benchmarks/RevLib/QASM_compiled/decod24-v1_41.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v1_41_scheduled ../benchmarks/RevLib/QASM_compiled/decod24-v1_41_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v2_43 ../benchmarks/RevLib/QASM_compiled/decod24-v2_43.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v2_43_scheduled ../benchmarks/RevLib/QASM_compiled/decod24-v2_43_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v3_45 ../benchmarks/RevLib/QASM_compiled/decod24-v3_45.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b decod24-v3_45_scheduled ../benchmarks/RevLib/QASM_compiled/decod24-v3_45_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b dist_223 ../benchmarks/RevLib/QASM_compiled/dist_223.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b dist_223_scheduled ../benchmarks/RevLib/QASM_compiled/dist_223_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex-1_166 ../benchmarks/RevLib/QASM_compiled/ex-1_166.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex-1_166_scheduled ../benchmarks/RevLib/QASM_compiled/ex-1_166_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex1_226 ../benchmarks/RevLib/QASM_compiled/ex1_226.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex1_226_scheduled ../benchmarks/RevLib/QASM_compiled/ex1_226_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex2_227 ../benchmarks/RevLib/QASM_compiled/ex2_227.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex2_227_scheduled ../benchmarks/RevLib/QASM_compiled/ex2_227_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex3_229 ../benchmarks/RevLib/QASM_compiled/ex3_229.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ex3_229_scheduled ../benchmarks/RevLib/QASM_compiled/ex3_229_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b f2_232 ../benchmarks/RevLib/QASM_compiled/f2_232.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b f2_232_scheduled ../benchmarks/RevLib/QASM_compiled/f2_232_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b graycode6_47 ../benchmarks/RevLib/QASM_compiled/graycode6_47.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b graycode6_47_scheduled ../benchmarks/RevLib/QASM_compiled/graycode6_47_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ham15_107 ../benchmarks/RevLib/QASM_compiled/ham15_107.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ham15_107_scheduled ../benchmarks/RevLib/QASM_compiled/ham15_107_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ham3_102 ../benchmarks/RevLib/QASM_compiled/ham3_102.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ham3_102_scheduled ../benchmarks/RevLib/QASM_compiled/ham3_102_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ham7_104 ../benchmarks/RevLib/QASM_compiled/ham7_104.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b ham7_104_scheduled ../benchmarks/RevLib/QASM_compiled/ham7_104_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb4_49 ../benchmarks/RevLib/QASM_compiled/hwb4_49.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb4_49_scheduled ../benchmarks/RevLib/QASM_compiled/hwb4_49_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb5_53 ../benchmarks/RevLib/QASM_compiled/hwb5_53.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb5_53_scheduled ../benchmarks/RevLib/QASM_compiled/hwb5_53_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb6_56 ../benchmarks/RevLib/QASM_compiled/hwb6_56.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb6_56_scheduled ../benchmarks/RevLib/QASM_compiled/hwb6_56_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb7_59 ../benchmarks/RevLib/QASM_compiled/hwb7_59.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb7_59_scheduled ../benchmarks/RevLib/QASM_compiled/hwb7_59_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb8_113 ../benchmarks/RevLib/QASM_compiled/hwb8_113.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb8_113_scheduled ../benchmarks/RevLib/QASM_compiled/hwb8_113_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb9_119 ../benchmarks/RevLib/QASM_compiled/hwb9_119.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b hwb9_119_scheduled ../benchmarks/RevLib/QASM_compiled/hwb9_119_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b inc_237 ../benchmarks/RevLib/QASM_compiled/inc_237.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b inc_237_scheduled ../benchmarks/RevLib/QASM_compiled/inc_237_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b life_238 ../benchmarks/RevLib/QASM_compiled/life_238.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b life_238_scheduled ../benchmarks/RevLib/QASM_compiled/life_238_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b majority_239 ../benchmarks/RevLib/QASM_compiled/majority_239.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b majority_239_scheduled ../benchmarks/RevLib/QASM_compiled/majority_239_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b max46_240 ../benchmarks/RevLib/QASM_compiled/max46_240.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b max46_240_scheduled ../benchmarks/RevLib/QASM_compiled/max46_240_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b miller_11 ../benchmarks/RevLib/QASM_compiled/miller_11.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b miller_11_scheduled ../benchmarks/RevLib/QASM_compiled/miller_11_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mini-alu_167 ../benchmarks/RevLib/QASM_compiled/mini-alu_167.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mini-alu_167_scheduled ../benchmarks/RevLib/QASM_compiled/mini-alu_167_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mini_alu_305 ../benchmarks/RevLib/QASM_compiled/mini_alu_305.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mini_alu_305_scheduled ../benchmarks/RevLib/QASM_compiled/mini_alu_305_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b misex1_241 ../benchmarks/RevLib/QASM_compiled/misex1_241.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b misex1_241_scheduled ../benchmarks/RevLib/QASM_compiled/misex1_241_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mlp4_245 ../benchmarks/RevLib/QASM_compiled/mlp4_245.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mlp4_245_scheduled ../benchmarks/RevLib/QASM_compiled/mlp4_245_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod10_171 ../benchmarks/RevLib/QASM_compiled/mod10_171.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod10_171_scheduled ../benchmarks/RevLib/QASM_compiled/mod10_171_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod10_176 ../benchmarks/RevLib/QASM_compiled/mod10_176.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod10_176_scheduled ../benchmarks/RevLib/QASM_compiled/mod10_176_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5adder_127 ../benchmarks/RevLib/QASM_compiled/mod5adder_127.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5adder_127_scheduled ../benchmarks/RevLib/QASM_compiled/mod5adder_127_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5d1_63 ../benchmarks/RevLib/QASM_compiled/mod5d1_63.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5d1_63_scheduled ../benchmarks/RevLib/QASM_compiled/mod5d1_63_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5d2_64 ../benchmarks/RevLib/QASM_compiled/mod5d2_64.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5d2_64_scheduled ../benchmarks/RevLib/QASM_compiled/mod5d2_64_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5mils_65 ../benchmarks/RevLib/QASM_compiled/mod5mils_65.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod5mils_65_scheduled ../benchmarks/RevLib/QASM_compiled/mod5mils_65_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod8-10_177 ../benchmarks/RevLib/QASM_compiled/mod8-10_177.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod8-10_177_scheduled ../benchmarks/RevLib/QASM_compiled/mod8-10_177_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod8-10_178 ../benchmarks/RevLib/QASM_compiled/mod8-10_178.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b mod8-10_178_scheduled ../benchmarks/RevLib/QASM_compiled/mod8-10_178_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v0_97 ../benchmarks/RevLib/QASM_compiled/one-two-three-v0_97.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v0_97_scheduled ../benchmarks/RevLib/QASM_compiled/one-two-three-v0_97_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v0_98 ../benchmarks/RevLib/QASM_compiled/one-two-three-v0_98.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v0_98_scheduled ../benchmarks/RevLib/QASM_compiled/one-two-three-v0_98_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v1_99 ../benchmarks/RevLib/QASM_compiled/one-two-three-v1_99.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v1_99_scheduled ../benchmarks/RevLib/QASM_compiled/one-two-three-v1_99_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v2_100 ../benchmarks/RevLib/QASM_compiled/one-two-three-v2_100.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v2_100_scheduled ../benchmarks/RevLib/QASM_compiled/one-two-three-v2_100_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v3_101 ../benchmarks/RevLib/QASM_compiled/one-two-three-v3_101.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b one-two-three-v3_101_scheduled ../benchmarks/RevLib/QASM_compiled/one-two-three-v3_101_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b plus63mod4096_163 ../benchmarks/RevLib/QASM_compiled/plus63mod4096_163.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b plus63mod4096_163_scheduled ../benchmarks/RevLib/QASM_compiled/plus63mod4096_163_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b plus63mod8192_164 ../benchmarks/RevLib/QASM_compiled/plus63mod8192_164.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b plus63mod8192_164_scheduled ../benchmarks/RevLib/QASM_compiled/plus63mod8192_164_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b pm1_249 ../benchmarks/RevLib/QASM_compiled/pm1_249.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b pm1_249_scheduled ../benchmarks/RevLib/QASM_compiled/pm1_249_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b qisa_opcodes ../benchmarks/RevLib/QASM_compiled/qisa_opcodes.qmap
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b radd_250 ../benchmarks/RevLib/QASM_compiled/radd_250.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b radd_250_scheduled ../benchmarks/RevLib/QASM_compiled/radd_250_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd32_270 ../benchmarks/RevLib/QASM_compiled/rd32_270.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd32_270_scheduled ../benchmarks/RevLib/QASM_compiled/rd32_270_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd32-v0_66 ../benchmarks/RevLib/QASM_compiled/rd32-v0_66.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd32-v0_66_scheduled ../benchmarks/RevLib/QASM_compiled/rd32-v0_66_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd32-v1_68 ../benchmarks/RevLib/QASM_compiled/rd32-v1_68.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd32-v1_68_scheduled ../benchmarks/RevLib/QASM_compiled/rd32-v1_68_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_130 ../benchmarks/RevLib/QASM_compiled/rd53_130.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_130_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_130_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_131 ../benchmarks/RevLib/QASM_compiled/rd53_131.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_131_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_131_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_133 ../benchmarks/RevLib/QASM_compiled/rd53_133.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_133_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_133_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_135 ../benchmarks/RevLib/QASM_compiled/rd53_135.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_135_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_135_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_138 ../benchmarks/RevLib/QASM_compiled/rd53_138.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_138_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_138_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_251 ../benchmarks/RevLib/QASM_compiled/rd53_251.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_251_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_251_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_311 ../benchmarks/RevLib/QASM_compiled/rd53_311.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd53_311_scheduled ../benchmarks/RevLib/QASM_compiled/rd53_311_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd73_140 ../benchmarks/RevLib/QASM_compiled/rd73_140.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd73_140_scheduled ../benchmarks/RevLib/QASM_compiled/rd73_140_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd73_252 ../benchmarks/RevLib/QASM_compiled/rd73_252.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd73_252_scheduled ../benchmarks/RevLib/QASM_compiled/rd73_252_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd84_142 ../benchmarks/RevLib/QASM_compiled/rd84_142.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd84_142_scheduled ../benchmarks/RevLib/QASM_compiled/rd84_142_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd84_253 ../benchmarks/RevLib/QASM_compiled/rd84_253.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b rd84_253_scheduled ../benchmarks/RevLib/QASM_compiled/rd84_253_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b root_255 ../benchmarks/RevLib/QASM_compiled/root_255.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b root_255_scheduled ../benchmarks/RevLib/QASM_compiled/root_255_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sao2_257 ../benchmarks/RevLib/QASM_compiled/sao2_257.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sao2_257_scheduled ../benchmarks/RevLib/QASM_compiled/sao2_257_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sf_274 ../benchmarks/RevLib/QASM_compiled/sf_274.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sf_274_scheduled ../benchmarks/RevLib/QASM_compiled/sf_274_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sf_276 ../benchmarks/RevLib/QASM_compiled/sf_276.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sf_276_scheduled ../benchmarks/RevLib/QASM_compiled/sf_276_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sqn_258 ../benchmarks/RevLib/QASM_compiled/sqn_258.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sqn_258_scheduled ../benchmarks/RevLib/QASM_compiled/sqn_258_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sqrt8_260 ../benchmarks/RevLib/QASM_compiled/sqrt8_260.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sqrt8_260_scheduled ../benchmarks/RevLib/QASM_compiled/sqrt8_260_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b squar5_261 ../benchmarks/RevLib/QASM_compiled/squar5_261.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b squar5_261_scheduled ../benchmarks/RevLib/QASM_compiled/squar5_261_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b square_root_7 ../benchmarks/RevLib/QASM_compiled/square_root_7.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b square_root_7_scheduled ../benchmarks/RevLib/QASM_compiled/square_root_7_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym10_262 ../benchmarks/RevLib/QASM_compiled/sym10_262.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym10_262_scheduled ../benchmarks/RevLib/QASM_compiled/sym10_262_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym6_145 ../benchmarks/RevLib/QASM_compiled/sym6_145.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym6_145_scheduled ../benchmarks/RevLib/QASM_compiled/sym6_145_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym6_316 ../benchmarks/RevLib/QASM_compiled/sym6_316.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym6_316_scheduled ../benchmarks/RevLib/QASM_compiled/sym6_316_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym9_146 ../benchmarks/RevLib/QASM_compiled/sym9_146.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym9_146_scheduled ../benchmarks/RevLib/QASM_compiled/sym9_146_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym9_148 ../benchmarks/RevLib/QASM_compiled/sym9_148.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym9_148_scheduled ../benchmarks/RevLib/QASM_compiled/sym9_148_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym9_193 ../benchmarks/RevLib/QASM_compiled/sym9_193.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sym9_193_scheduled ../benchmarks/RevLib/QASM_compiled/sym9_193_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sys6-v0_111 ../benchmarks/RevLib/QASM_compiled/sys6-v0_111.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b sys6-v0_111_scheduled ../benchmarks/RevLib/QASM_compiled/sys6-v0_111_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf1_149 ../benchmarks/RevLib/QASM_compiled/urf1_149.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf1_149_scheduled ../benchmarks/RevLib/QASM_compiled/urf1_149_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf1_278 ../benchmarks/RevLib/QASM_compiled/urf1_278.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf1_278_scheduled ../benchmarks/RevLib/QASM_compiled/urf1_278_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf2_152 ../benchmarks/RevLib/QASM_compiled/urf2_152.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf2_152_scheduled ../benchmarks/RevLib/QASM_compiled/urf2_152_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf2_277 ../benchmarks/RevLib/QASM_compiled/urf2_277.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf2_277_scheduled ../benchmarks/RevLib/QASM_compiled/urf2_277_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf3_155 ../benchmarks/RevLib/QASM_compiled/urf3_155.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf3_155_scheduled ../benchmarks/RevLib/QASM_compiled/urf3_155_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf3_279 ../benchmarks/RevLib/QASM_compiled/urf3_279.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf3_279_scheduled ../benchmarks/RevLib/QASM_compiled/urf3_279_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf4_187 ../benchmarks/RevLib/QASM_compiled/urf4_187.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf4_187_scheduled ../benchmarks/RevLib/QASM_compiled/urf4_187_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf5_158 ../benchmarks/RevLib/QASM_compiled/urf5_158.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf5_158_scheduled ../benchmarks/RevLib/QASM_compiled/urf5_158_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf5_280 ../benchmarks/RevLib/QASM_compiled/urf5_280.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf5_280_scheduled ../benchmarks/RevLib/QASM_compiled/urf5_280_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf6_160 ../benchmarks/RevLib/QASM_compiled/urf6_160.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b urf6_160_scheduled ../benchmarks/RevLib/QASM_compiled/urf6_160_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b wim_266 ../benchmarks/RevLib/QASM_compiled/wim_266.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b wim_266_scheduled ../benchmarks/RevLib/QASM_compiled/wim_266_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b xor5_254 ../benchmarks/RevLib/QASM_compiled/xor5_254.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b xor5_254_scheduled ../benchmarks/RevLib/QASM_compiled/xor5_254_scheduled.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b z4_268 ../benchmarks/RevLib/QASM_compiled/z4_268.qasm
python ../../quapa/tools/qasm_analyzer.py -c benchmarks_profile.csv -e png -o ./data -b z4_268_scheduled ../benchmarks/RevLib/QASM_compiled/z4_268_scheduled.qasm
