OPENQASM 2.0;
include "qelib1.inc";
qreg[8];
creg[8];
  x q[0];
  x q[7];
  x q[0];
  cx q[1], q[4];
  cx q[1], q[0];
  toffoli q[0], q[4], q[1];
  cx q[2], q[5];
  cx q[2], q[1];
  toffoli q[1], q[5], q[2];
  cx q[3], q[7];
  x q[5];
  cx q[1], q[5];
  toffoli q[1], q[5], q[2];
  x q[5];
  cx q[2], q[1];
  cx q[2], q[5];
  x q[4];
  cx q[0], q[4];
  toffoli q[0], q[4], q[1];
  x q[4];
  cx q[1], q[0];
  cx q[1], q[4];
  measure q[0];
  measure q[1];
  measure q[2];
  measure q[3];
  measure q[4];
  measure q[5];
  measure q[6];
  measure q[7];
